language: c
dist: xenial

addons:
        apt:
                packages:
                        - libelf-dev
                        - bc
                        - bison
                        - flex
                        - codespell
                        - ocaml
                        - automake
                        - autoconf

matrix:
        include:
                env: KERNEL_VERSION=4.20-rc3 KERNEL_ARCHIVE=gz

cache:
        directories:
                - $HOME/bin
                - $HOME/.opam

before_install:
        - sparse --version || ( git clone git://git.kernel.org/pub/scm/devel/sparse/sparse.git && cd sparse && make HAVE_LLVM='no' install && cd - )
        - spatch --version || ( wget --quiet https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s $HOME/bin 4.05.0 && eval $(opam config env) && opam install -y pcre.7.1.1 menhir && git clone https://github.com/coccinelle/coccinelle.git && cd coccinelle && ./autogen && ./configure --prefix=$HOME --without-bash-completion && make install && cd - )

before_script:
        - export KTDIR="$(pwd)"
        - ./contrib/kernel-tree/create-patch.sh > katechon.patch
        - cd ..
        # kernel configuration
        - wget --quiet https://git.kernel.org/torvalds/t/linux-$KERNEL_VERSION.tar.$KERNEL_ARCHIVE
        - tar xf linux-$KERNEL_VERSION.tar.$KERNEL_ARCHIVE
        - export KERNELDIR="$(pwd)/linux-$KERNEL_VERSION"
        - cd $KERNELDIR
        - patch -p1 < "$KTDIR/katechon.patch"
        - make defconfig
        - sed -i 's/^# CONFIG_SECURITY_KATECHON is not set/CONFIG_SECURITY_KATECHON=y/' .config
        - make olddefconfig
        - make modules_prepare


script:
        - cd "$KTDIR/src"
        - make
        - make style
        - make check
        - eval $(opam config env) && make coccicheck
